"""add image_url to event

Revision ID: 1b4c4b24570b
Revises: 3bbc5923dcf4
Create Date: 2025-05-20 12:33:21.935143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4c4b24570b'
down_revision: Union[str, None] = '3bbc5923dcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_image')
    # ### end Alembic commands ###
