"""fix relationship

Revision ID: 25c4cc4638cb
Revises: e05da6c63605
Create Date: 2025-06-08 20:17:44.379699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c4cc4638cb'
down_revision: Union[str, None] = 'e05da6c63605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('event_category_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_category_id_fkey', 'event', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.alter_column('event', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
