"""add date index

Revision ID: e05da6c63605
Revises: afa1861d4608
Create Date: 2025-06-08 14:41:30.792286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05da6c63605'
down_revision: Union[str, None] = 'afa1861d4608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_date_date'), 'event_date', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_date_date'), table_name='event_date')
    # ### end Alembic commands ###
