"""add plural name category

Revision ID: ea2bea8905bf
Revises: 1b4c4b24570b
Create Date: 2025-05-20 16:35:29.954591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2bea8905bf'
down_revision: Union[str, None] = '1b4c4b24570b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('plural_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'plural_name')
    # ### end Alembic commands ###
